# pip install --upgrade mkdocs mkdocstrings-python markdown-include
# mkdocs serve -a 0.0.0.0:8000
# dev_addr: 0.0.0.0:8000
site_name: llama-client-aic - distributed llms
site_url: https://llama-client-aic.readthedocs.io/en/latest/
repo_url: https://github.com/redten/llama-client-aic
edit_uri: https://github.com/redten/llama-client-aic/blob/main/docs/
site_description: A distributed LLM platform for building and training models on-premise or hybrid (where the expensive gpu clusters are on a cloud provider). Helps find knowledge gaps and blindspots while enabling structured and unstructured datasets to tune response quality over many LLM testing generations.
site_author: redten

# https://www.mkdocs.org/user-guide/configuration/#documentation-layout
theme:
  name: readthedocs
  # name: mkdocs
  # locale: en
  # https://www.mkdocs.org/user-guide/choosing-your-theme/
  analytics:
    gtag: G-5WXGL4TV74
  highlightjs: true
  features:
  - navigation.expand
  - navigation.path
  - toc.integrate

# submodules:
#  include: all
#  recursive: true

nav:
- Introduction: index.md
- Examples:
  - examples/how-do-I-ask-the-LLM-questions?.md
- Authentication and User Creation:
  - sdk/authenticate-with-the-rlhf-llm-rest-api.md
- Self-Hosted SDK:
  - sdk/ask-a-self-hosted-llm-a-question-with-rag-and-rlhf-and-store-the-ai-testing-results-in-a-database.md
  - sdk/search-for-my-previous-llm-ai-results.md
- Hybrid with the GPU Cluster on a Cloud:
  - sdk/guides/use-a-remote-llm-agent-to-store-results-on-premise.md
- Running Locally: 
  - sdk/setup-environment-variables-for-a-dev-environment.md
- Models and Schema: 
  - sdk/models/CoreResultAI.md
  - sdk/models/CoreSearchResultAI.md
  - sdk/models/CoreJob.md
  - sdk/models/CoreResultJob.md
  - sdk/models/CoreUser.md
- LLM Job Management: 
  - sdk/llm-distributed-job-management-api.md
- User Management: 
  - sdk/multi-tenant-user-management-api.md
- Encryption in Transit: 
  - sdk/tls/encryption-in-transit.md
extra:
  version: "1.0.0"
plugins:
- search
# https://mkdocstrings.github.io/usage/#finding-out-the-anchor
- autorefs
- mkdocstrings:
    handlers:
      # See: https://mkdocstrings.github.io/python/usage/
      python:
        options:
          docstring_style: sphinx
          # https://mkdocstrings.github.io/python/usage/configuration/headings/
          # show_root_toc_entry: true
          # heading_level: 6
        paths:
        - client_aic
        - client_aic.config
        - client_aic.models
        - client_aic.req
        - client_aic.req.ai
        - client_aic.req.auth
        - client_aic.req.job
        - client_aic.req.user
        - client_aic.tls
        - examples
markdown_extensions:
- markdown_include.include:
    base_path: .
- admonition
# - toc:
#    toc_depth: 6
